apiVersion: v1
kind: Service
metadata:
  name: driver-db
  namespace: data-prod
spec:
  ports:
    - port: 5432
  selector:
    app: driver-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: driver-db
  namespace: data-prod
spec:
  serviceName: driver-db
  replicas: 1
  selector:
    matchLabels:
      app: driver-db
  template:
    metadata:
      labels:
        app: driver-db
    spec:
      securityContext:
        fsGroup: 70
      containers:
        - name: driver-db-postgres
          securityContext:
            runAsUser: 70
            runAsGroup: 70
            runAsNonRoot: true
          image: docker.io/postgres:18-alpine
          args:
            - "-c"
            - "wal_level=logical"
            - "-c"
            - "max_replication_slots=4"
            - "-c"
            - "max_wal_senders=4"
          env:
            - name: POSTGRES_DB
              value: driver_db
            - name: POSTGRES_USER
              value: karga
            - name: POSTGRES_PASSWORD_FILE
              value: "/etc/secrets/driver_db_password"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "karga", "-d", "driver_db" ]
            initialDelaySeconds: 30
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "karga", "-d", "driver_db" ]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: driver-db-data
              mountPath: /var/lib/postgresql/data
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: driver-db-secret
  volumeClaimTemplates:
    - metadata:
        name: driver-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi