apiVersion: v1
kind: Service
metadata:
  name: driver-db
  namespace: data-prod
spec:
  ports:
    - port: 5432
  selector:
    app: driver-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: driver-db
spec:
  serviceName: driver-db
  replicas: 1
  selector:
    matchLabels:
      app: driver-db
  template:
    metadata:
      labels:
        app: driver-db
    spec:
      containers:
        - name: driver-db-postgres
          image: docker.io/postgres:18-alpine
          env:
            - name: POSTGRES_DB
              value: driver_db
            - name: POSTGRES_USER
              value: karga
            - name: POSTGRES_PASSWORD_FILE
              value: "/etc/secrets/driver_db_password"
          volumeMounts:
            - name: driver-db-data
              mountPath: /var/lib/postgresql
            - name: secret-volume
              mountPath: /etc/secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: karga-secrets
  volumeClaimTemplates:
    - metadata:
        name: driver-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi

