apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: mon-prod
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki.mon-prod.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [ __meta_kubernetes_pod_node_name ]
            target_label: __host__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [ __meta_kubernetes_namespace ]
            target_label: namespace
          - action: replace
            source_labels: [ __meta_kubernetes_pod_name ]
            target_label: pod
          - action: replace
            source_labels: [ __meta_kubernetes_container_name ]
            target_label: container
          - source_labels: [ __meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name ]
            action: replace
            target_label: __path__
            separator: /
            replacement: /var/log/pods/*$1/*.log
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: mon-prod
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-acc
      containers:
        - name: promtail
          image: docker.io/grafana/promtail:2.9.2
          securityContext:
            runAsUser: 0
            privileged: true
          args: [ "-config.file=/etc/promtail/promtail.yaml" ]
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - name: pods-logs
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: run
          hostPath:
            path: /run/promtail
        - name: pods-logs
          hostPath:
            path: /var/log/pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-acc
  namespace: mon-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-Crole
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "nodes/proxy", "services", "endpoints", "pods" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-Crolebinding
subjects:
  - kind: ServiceAccount
    name: promtail-acc
    namespace: mon-prod
roleRef:
  kind: ClusterRole
  name: promtail-Crole
  apiGroup: rbac.authorization.k8s.io