apiVersion: v1
kind: Service
metadata:
  name: karga-redis
  namespace: data-prod
spec:
  ports:
    - port: 6379
      name: client
  selector:
    app: karga-redis
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: karga-redis
  namespace: data-prod
spec:
  serviceName: karga-redis
  replicas: 1
  selector:
    matchLabels:
      app: karga-redis
  template:
    metadata:
      labels:
        app: karga-redis
    spec:
      containers:
        - name: karga-redis
          image: docker.io/redis:7-alpine
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              mkdir -p /usr/local/etc/redis &&
              echo "user default off" > /usr/local/etc/redis/users.acl &&
              echo "user $(cat /etc/secrets/redis_username) on >$(cat /etc/secrets/redis_password) ~* +@all -@admin -@dangerous +info" >> /usr/local/etc/redis/users.acl &&
              redis-server --aclfile /usr/local/etc/redis/users.acl --appendonly yes
          ports:
            - containerPort: 6379
              name: client
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "redis-cli -u redis://$(cat /etc/secrets/redis_username):$(cat /etc/secrets/redis_password)@localhost:6379 ping | grep PONG"
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "redis-cli -u redis://$(cat /etc/secrets/redis_username):$(cat /etc/secrets/redis_password)@localhost:6379 ping | grep PONG"
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: redis-db-secret

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi