apiVersion: v1
kind: Secret
metadata:
  name: karga-secrets
  namespace: data-prod
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "app-prod/karga-secrets"
---
apiVersion: v1
kind: Secret
metadata:
  name: karga-secrets
  namespace: app-prod
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "data-prod"
type: Opaque
stringData:
  auth_db_password: "your_auth_db_password"
  driver_db_password: "your_driver_db_password"
  payment_db_password: "your_payment_db_password"
  redis_password: "your_redis_password"
  redis_username: "default"
  stripe_api_key: "your_stripe_api_key"
  stripe_webhook_secret: "your_stripe_webhook_secret"
  trip_db_password: "your_trip_db_password"
  user_db_password: "your_user_db_password"