apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store
  namespace: data-prod
spec:
  provider:
    vault:
      server: "https://192.168.49.1:8200"

      path: secret
      version: v2

      caProvider:
        type: Secret
        name: vault-ca
        namespace: data-prod
        key: vault.crt

      auth:
        tokenSecretRef:
          name: vault-token
          namespace: data-prod
          key: token
