apiVersion: v1
kind: Service
metadata:
  name: vault-server
  namespace: app-prod
spec:
  ports:
    - port: 8200
      targetPort: 8200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vault-server
  namespace: app-prod
subsets:
  - addresses:
      - ip: 192.168.49.1
    ports:
      - port: 8200